### ISSUE TITLE
PDA/Supply Shuttle Console breaks after using cyrillic

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#4557]
**Problem Description**:
PDA/Supply Shuttle Console (every NanoUI console with text input feature) breaks after using cyrillic (when you writing down the reason for order or messanging someone). It breaks even without using problematic "ÿ", so i think it's not usual byond issue with 255 reserved sybmol.

**What did you expect to happen**: 
Normal Supply Shuttle Console/PDA window.

**What happened instead**:
Empty NanoUI screen.

**Why is this bad/What are the consequences:**
You can't use Supply Shuttle Console. You can't use PDA. Fix NanoUI button does nothing.

**Steps to reproduce the problem**:
1. Open Supply Shuttle Console
2. Order something.
3. In the order reason popup write this (just copy the text): тест
4. Now reopen the console.
5. Now you see the blank window with NT logo.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Tried to find the function which causes problems and found that nano.js can't read property 'hasOwnProperty' of undefined (line 144):
`t.config.hasOwnProperty("stateKey") && t.config.stateKey && (n = t.config.stateKey.toLowerCase())`

**Comment by CrAzYPiLoT-SS13** [comment]
I don't know if this is another one of those mistakes, or a real issue, but
Paradise was never meant for Cyrillic. I know of an old Russian server
called Tau Ceti which had full Cyrillic support in every aspect. If it
still exists, see if you can get some code from it ;)

**Comment by Injazz** [comment]
@CrAzYPiLoT-SS13 cyrillic symbols can break consoles and PDA and make game unplayable for Cargo, or HoP, so i think it would be good if input window will have some kind of restriction on cyrillic symbols.

I think the issue come from 510 and features likes this #4332 , and Tau Ceti doesn't using these features yet.

**Comment by CrAzYPiLoT-SS13** [comment]
I am sorry to hear that, but this is the first time and, maybe the only
time, we have had this problem, as the server language itself is a hint
that we use latin characters not cyrillic. Even if someone would take on
the task to add comments about unicode restrictions to every input that
exists, it would make them look ugly and probably wouldn't get past the
maintainers. Again, this_is_ a problem, although a problem we will maybe
never see again and that can probably be fixed with a simple ahelp or a
reconnect.

**Comment by PJB3005** [comment]
The Cyrillic is being fucked up because BYOND doesn't support it, and whatever junk it turns out as breaks nano. Sounds like it should be feasible to fix the console breaking but you still won't be able to use Cyrillic at all.

**Comment by CrAzYPiLoT-SS13** [comment]
All that I can think of is add a warning to the MOTD about using non-UTF-8 characters in inputs. From what I see, we won't be able to do anything more than that about it. As for your server, have you thought about reverting #4332 on your repo?

**Comment by PJB3005** [comment]
If anybody wants to fix this, port libvg from /vg/station for UTF-8 handling, and run supply shuttle input through `strict_ascii`

**Comment by AffectedArc07** [comment]
BYOND supports unicode now.
